version: '3'

services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    networks:
      cassandra_network:
        ipv4_address: 192.168.1.200
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraCluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=Rack1
    ports:
      - "9042:9042" # порт для подключения через cqlsh
    volumes:
      - cassandra1-data:/var/lib/cassandra

  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    networks:
      cassandra_network:
        ipv4_address: 192.168.1.201
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraCluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=Rack1
    ports:
      - "9043:9042" # доступ для cqlsh на другом порту
    volumes:
      - cassandra2-data:/var/lib/cassandra

  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    networks:
      cassandra_network:
        ipv4_address: 192.168.1.202
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraCluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=Rack1
    ports:
      - "9044:9042" # доступ для cqlsh на другом порту
    volumes:
      - cassandra3-data:/var/lib/cassandra

networks:
  cassandra_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

volumes:
  cassandra1-data:
  cassandra2-data:
  cassandra3-data:
